export const GET_CART_REQUSET = "GET_CART_REQUSET"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"

export const ADJUST_QTY_REQUEST = "ADJUST_QTY_REQUEST"
export const ADJUST_QTY_SUCCESS = "ADJUST_QTY_SUCCESS"
export const ADJUST_QTY_FAIL = "ADJUST_QTY_FAIL"

export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS"
export const DELETE_CART_FAIL = "DELETE_CART_FAIL"